import { Typography, Card, CardMedia, CardContent, CardActions, Button, Grid } from '@material-ui/core'
import { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import http from '../http';
import { Product } from '../model'

interface ProductsListPageProps  {
  products: Product[];
}

const ProductsListPage: NextPage<ProductsListPageProps> = ({ products }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
        Product
      </Typography>
      Listagem de produtos
      <Grid container spacing={4}>
        {products.map((product, key) => (
          <Grid key={key} item xs={12} sm={6} md={4}>
            <Card>
              <CardMedia
                style={{ paddingTop: "56%" }}
                image={product.image_url}
              />
              <CardContent>
                <Typography component="h2" variant="h5" gutterBottom>
                  {product.name}
                </Typography>
              </CardContent>
              <CardActions>
                <Link
                  href="/products/[slug]"
                  as={`/products/${product.slug}`}
                  passHref
                >
                  <Button size="small" color="primary" component="a">
                    Detalhes
                  </Button>
                </Link>
              </CardActions>
            </Card>
          </Grid>
        ))}
      </Grid>
    </div>
  )
}

export default ProductsListPage;

export const getServerSideProps: GetServerSideProps<ProductsListPageProps> = async (context) => {
  const response = await http.get('products')
  return {
    props: {
      products: response.data
    }
  }
}